name: tradetitan
description: "Trade Titan"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  fl_chart: ^1.1.1
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  intl: ^0.20.2
  glassmorphism: ^3.0.0
  smooth_page_indicator: ^1.2.1
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
